import { NgModule } from '@angular/core';

// material angular
import {
    MatButtonModule,
    MatCardModule,
    MatBadgeModule,
    MatMenuModule,
    MatIconModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatTabsModule,
    MatFormFieldModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatAutocompleteModule,
    MatNativeDateModule,
    MatDialogModule,
    MatDividerModule,
    MatSelectModule,
    MatSnackBarModule,
} from '@angular/material';

@NgModule({
    imports: [
        MatButtonModule,
        MatCardModule,
        MatBadgeModule,
        MatMenuModule,
        MatIconModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatTabsModule,
        MatFormFieldModule,
        MatInputModule,
        MatProgressSpinnerModule,
        MatExpansionModule,
        MatDatepickerModule,
        MatAutocompleteModule,
        MatNativeDateModule,
        MatDialogModule,
        MatDividerModule,
        MatSelectModule,
        MatSnackBarModule,
    ],
    exports: [
        MatButtonModule,
        MatCardModule,
        MatBadgeModule,
        MatMenuModule,
        MatIconModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatTabsModule,
        MatFormFieldModule,
        MatInputModule,
        MatProgressSpinnerModule,
        MatExpansionModule,
        MatDatepickerModule,
        MatAutocompleteModule,
        MatNativeDateModule,
        MatDialogModule,
        MatDividerModule,
        MatSelectModule,
        MatSnackBarModule,
    ]
})
export class MaterialModule { }